### ISSUE TITLE
Add WCS to metadata in create_wfi_image

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/roman_datamodels#134]
Over in jdaviz we're working on supporting Roman L2 data products (spacetelescope/jdaviz#1822). I've been testing our Roman ASDF support on some old SOC build files, but having smaller/artificial `ImageModel`s would be helpful. Today I came across `rdm.testing.factors.create_wfi_image`, which nearly does what we need!

On main, the synthetic WFI image created by this method only has a `photometry` key in the metadata, but no `wcs`:

https://github.com/spacetelescope/roman_datamodels/blob/932afed416e02bf0e684973f03548eeefe973b9e/src/roman_datamodels/testing/factories.py#L1259

Would it be possible to add a simple WCS, too? We do something [like this in jdaviz for testing](https://github.com/spacetelescope/jdaviz/blob/f92fcb2d7bad74ad6265321b8e7ea2e00dc977a5/jdaviz/conftest.py#L48-L52).

Thanks!

**Comment by bmorris3** [comment]
From some further reading, it looks like [full WCS is stored for Level 2 products but not for Level 1](https://github.com/spacetelescope/roman_datamodels/blob/932afed416e02bf0e684973f03548eeefe973b9e/docs/roman_datamodels/datamodels/general_structure.rst#level-2-example). Are there other important subtleties that might make `create_wfi_image` inappropriate for use for synthetic test data generation?

**Comment by PaulHuwe** [comment]
The utilities you want for making models (and/or files) are located in maker_utils.py:

Level 1
https://github.com/spacetelescope/roman_datamodels/blob/main/src/roman_datamodels/maker_utils.py#L427

Level 2
https://github.com/spacetelescope/roman_datamodels/blob/main/src/roman_datamodels/maker_utils.py#L470

**Comment by PaulHuwe** [comment]
There are other subtleties - Level 1 files are simply the input to the pipeline, whereas Level 2 is output from any step from Ramp onwards (which may include models that lack WCS).

**Comment by bmorris3** [comment]
Thanks for the background @PaulHuwe. I've got an example which generates synthetic gwcs and attaches them to an `ImageModel` for a test in jdaviz, see [`create_example_gwcs`](https://github.com/spacetelescope/jdaviz/pull/1822/files#diff-f5a4063005206af0e8e140dcf2a9c9f544872797483f77150ae80da554e5e447R285) and https://github.com/spacetelescope/jdaviz/pull/1822#pullrequestreview-1351142503. Happy to add this to `maker_utils.py` if you like.

**Comment by ddavis-stsci** [comment]
I'm closing this issue since skymatch & jdaviz issues are closed.
