### ISSUE TITLE
Calls to missing (removed?) classes in testing module

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/roman_datamodels#136]
There are some references to `roman_datamodels.stnode.Wcsinfo`:

https://github.com/spacetelescope/roman_datamodels/blob/481c3e3aa8854e4bf7318d6222b8d85adf1ce776/src/roman_datamodels/testing/factories.py#L1177-L1203

but there is no `Wcsinfo` in `stnode` [on main](https://github.com/spacetelescope/roman_datamodels/blob/main/src/roman_datamodels/stnode.py).

**Comment by WilliamJamieson** [comment]
Correct `stnode`'s interface is dynamically generated during its first import based on structures laid out in the `rad` schemas.

**Comment by WilliamJamieson** [comment]
Note that the majority of things one imports from `stnode` are generated dynamically on the first import of `stnode` (wherever that happens) by this block: https://github.com/spacetelescope/roman_datamodels/blob/481c3e3aa8854e4bf7318d6222b8d85adf1ce776/src/roman_datamodels/stnode.py#L512-L560.

Essentially, it iterates through the tags in the `rad` manifest: https://github.com/spacetelescope/rad/blob/main/src/rad/resources/manifests/datamodels-1.0.yaml and generates an object from every entry in the `tags` list.

In particular, the `Wcsinfo` class is dynamically generated from this entry: https://github.com/spacetelescope/rad/blob/de6cb205fbe2757f5692c2b1e11db48261808c21/src/rad/resources/manifests/datamodels-1.0.yaml#L103-L107 in the `rad` manifest by this: https://github.com/spacetelescope/roman_datamodels/blob/481c3e3aa8854e4bf7318d6222b8d85adf1ce776/src/roman_datamodels/stnode.py#L535-L539. Following the logic backwards, when a `Wcsinfo` object is initialized it will form an object with structure based on: https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/wcsinfo-1.0.0.yaml.

**Comment by bmorris3** [comment]
Thanks for the tutorial @WilliamJamieson, I appreciate it!
