### ISSUE TITLE
random_utils need to let user set seed

### ISSUE THREAD

**Issue by pllim** [spacetelescope/roman_datamodels#144]
I don't see any way to set a seed for https://github.com/spacetelescope/roman_datamodels/blob/main/src/roman_datamodels/random_utils.py 

Also while you are at it, maybe use the new API: https://numpy.org/doc/stable/reference/random/generator.html

**Comment by WilliamJamieson** [comment]
Agreed.

**Comment by bmorris3** [comment]
@WilliamJamieson Can't we use [`random.seed`](https://docs.python.org/3/library/random.html#random.seed)?

**Comment by WilliamJamieson** [comment]
That should reset the random seed for the classic numpy random number generator.

**Comment by bmorris3** [comment]
The current implementation of `random_utils` generates scalars with the `random` package, and separately generates vectors with `np.random`. It might be a lot cleaner/easier to debug if we dropped `random` in favor of `np.random`, and then you could just call `np.random.seed()`.
