### ISSUE TITLE
DOC: Add a section on file I/O

### ISSUE THREAD

**Issue by pllim** [spacetelescope/roman_datamodels#145]
In particular, I can't find the docs on how to write a `roman_datamodels.datamodels.ImageModel` out into `.asdf` file. I thought it would have a `.write` method but it does not. A search on "write" on the docs search bar took forever, not sure why.

**Comment by WilliamJamieson** [comment]
It should be `.to_asdf`

**Comment by ddavis-stsci** [comment]
I'm closing this since there has been no more activity since April 10.
