### ISSUE TITLE
Support Opening Datamodels as Another Type

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/roman_datamodels#22]
Add support for opening a datamodel as another type, and having everything "under the hood" matching the new type (eg. opening a WFI ScienceRaw Level 1 file/model as RampModel).

**Comment by perrygreenfield** [comment]
It has been decided for the time being that such conversions should be explicit in the calibration code. If it turns out that this is much more common than it was for JWST, we can reconsider adding this automatic conversion of models to the this package.
