### ISSUE TITLE
Metadata display

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/roman_datamodels#244]
In version 0.16.1 (the current released version on PyPI), typing metadata only returns an object instead of displaying the information. For example:

```
import roman_datamodels as rdm
test = rdm.open('r0000501001001001001_01101_0001_WFI01_cal.asdf')
test.meta.instrument
```

returns:
`<roman_datamodels.stnode.WfiMode at 0x11deeb6d0>`

rather than a nested representation of the content. Enclosing it like `dict(test.meta.instrument)` does print it out, but this is not like earlier behavior and will be not as useful for users. Can we have some way to display the nested data within metadata sections just by typing, e.g., `test.meta.instrument`?

**Comment by tddesjardins** [comment]
Oops, meant to tag @nden on this per her request.

**Comment by WilliamJamieson** [comment]
You mean something like [`.info`](https://github.com/spacetelescope/roman_datamodels/blob/59fc71b47bc65072aaf0d77f97d8d84310f6a683/src/roman_datamodels/datamodels/_core.py#L321-L322)?

It wraps the `.info` provided by ASDF, see: https://asdf.readthedocs.io/en/stable/api/asdf.info.html and https://asdf.readthedocs.io/en/stable/asdf/features.html#rendering-asdf-trees.

Alternately, a `__repr__` can be added, which is likely what made this work before.

**Comment by tddesjardins** [comment]
I think closer to a `__repr__` just something that prints out the contents of the object in a readable way. It doesn't have to do the actual nested, line-by-line, indented formatting of the `.info` method necessarily...but I also wouldn't say no if that's trivial to implement.

**Comment by WilliamJamieson** [comment]
> I think closer to a `__repr__` just something that prints out the contents of the object in a readable way. It doesn't have to do the actual nested, line-by-line, indented formatting of the `.info` method necessarily...but I also wouldn't say no if that's trivial to implement.

Yes, looking at the history this is my fault. I did not add `__repr__` as part of #191. It should be very easy to add one in.
