### ISSUE TITLE
Unable to open association file with `datamodels.open`

### ISSUE THREAD

**Issue by braingram** [spacetelescope/roman_datamodels#267]
Running:
```
import roman_datamodels.datamodels as dm
dm.open('r90001-a3001_image_001_asn.json')
```
Results in:
```
ile ~/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/asdf/asdf.py:1064, in AsdfFile._open_generic_file(cls, self, generic_file, uri, validate_checksums, extensions, _get_yaml_content, _force_raw_types, strict_extension_check, ignore_missing_extensions, **kwargs)
   1063 msg = "Input object does not appear to be an ASDF file or a FITS with ASDF extension"
-> 1064 raise ValueError(msg)

ValueError: Input object does not appear to be an ASDF file or a FITS with ASDF extension

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 dm.open('r90001-a3001_image_001_asn.json')

File ~/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/roman_datamodels/datamodels/_utils.py:93, in rdm_open(init, memmap, **kwargs)
     90 if "asn_n_members" in kwargs:
     91     del kwargs["asn_n_members"]
---> 93 asdf_file = init if isinstance(init, asdf.AsdfFile) else _open_path_like(init, memmap=memmap, **kwargs)
     94 if (model_type := type(asdf_file.tree["roman"])) in MODEL_REGISTRY:
     95     return MODEL_REGISTRY[model_type](asdf_file, **kwargs)

File ~/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/roman_datamodels/datamodels/_utils.py:54, in _open_path_like(init, memmap, **kwargs)
     52     asdf_file = asdf.open(init, **kwargs)
     53 except ValueError as err:
---> 54     raise TypeError("Open requires a filepath, file-like object, or Roman datamodel") from err
     56 # This is only needed until we move min asdf version to 3.0
     57 if AsdfInFits is not None and isinstance(asdf_file, AsdfInFits):

TypeError: Open requires a filepath, file-like object, or Roman datamodel
```

The error originates from `roman_datamodels` attempting to open the `json` file as as asdf file in `_open_path_like` here:
https://github.com/spacetelescope/roman_datamodels/blob/16c16d37d29c452594d0220f9c4801b465304419/src/roman_datamodels/datamodels/_utils.py#L93

There appears to be checks against the file suffix:
https://github.com/spacetelescope/roman_datamodels/blob/16c16d37d29c452594d0220f9c4801b465304419/src/roman_datamodels/datamodels/_utils.py#L97-L104
that occur after the call to `_open_path_like` (which only returns an `AsdfFile`), moving the suffix checks prior to `_open_path_like` was insufficient to fix the issue due to at least the following:
- the suffix comparison is against `json` not `.json`
- if the suffix comparison is fixed (replaced with `.json`) the functions returns a string
Having `rdm_open` return a string is incompatible with stpipe which expects that the return value can be used as a context and the following error is seen:
```
Traceback (most recent call last):
  File "/Users/bgraham/.pyenv/versions/romancal_doctests/bin/strun", line 26, in <module>
    step = Step.from_cmdline(sys.argv[1:])
  File "/Users/bgraham/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/stpipe/step.py", line 186, in from_cmdline
    return cmdline.step_from_cmdline(args)
  File "/Users/bgraham/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/stpipe/cmdline.py", line 375, in step_from_cmdline
    step, step_class, positional, debug_on_exception = just_the_step_from_cmdline(
  File "/Users/bgraham/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/stpipe/cmdline.py", line 308, in just_the_step_from_cmdline
    parameter_cfg = step_class.get_config_from_reference(
  File "/Users/bgraham/.pyenv/versions/3.10.6/envs/romancal_doctests/lib/python3.10/site-packages/stpipe/pipeline.py", line 182, in get_config_from_reference
    with cls._datamodels_open(dataset, asn_n_members=1) as model:
AttributeError: __enter__
```

**Comment by braingram** [comment]
One question about this.

@schlafly @PaulHuwe is this by design? Do we want:
- roman_datamodels to open associations as `ModelLibrary` (only if `romancal` is installed) similar to how [stdatamodels](https://github.com/spacetelescope/stdatamodels/blob/234413f1209c50b9b103239279c813fa678dec81/src/stdatamodels/jwst/datamodels/util.py#L124) returns a `ModelContainer` if jwst is installed.
- roman_datamodels to provide a more helpful error, maybe something like "roman_datamodels cannot open association files. Please use romancal.datamodels.ModelLibrary(fn)"

I'm thinking the second option makes sense.

**Comment by schlafly** [comment]
Sorry, I see that you're resurrecting this from last year!  We are clearly not using this feature.  My sense is that the first option is the most user friendly; return a ModelLibrary if romancal is installed.  But this clearly is not high priority.
