### ISSUE TITLE
create_wcs_image removed from main

### ISSUE THREAD

**Issue by Borlaff** [spacetelescope/roman_datamodels#323]
Hi, 

I am trying to follow the tutorial to generate a test WFI image using roman_datamodels: 

https://roman-pipeline.readthedocs.io/en/latest/roman/datamodels/models.html
```

from roman_datamodels import datamodels as rdm
from roman_datamodels.testing.factories import create_wfi_image
import numpy as np

image_node = create_wfi_image()
image_model = rdm.ImageModel(image_node)
type(image_model)
#<class 'roman_datamodels.datamodels.ImageModel'>
```

However in the latest version (0.19) nor the development version roman_datamodels-0.19.1.dev4+g087a60d
`AttributeError: module 'roman_datamodels.datamodels' has no attribute 'testing'`

Was this method removed or there is an equivalent and it has not been updated in the pydocs?

Thank you so much,

**Comment by nden** [comment]
It appears the documentation is out of sync with the code. We will fix this but meanwhile you can use something like

```
from roman_datamodels import datamodels as rdm
from roman_datamodels import maker_utils

l2 = maker_utils.mk_level2_image(shape=(2000, 2000))
l2_im = rdm.ImageModel(l2)
```

Please let us know if this does what you need.

**Comment by WilliamJamieson** [comment]
> It appears the documentation is out of sync with the code. We will fix this but meanwhile you can use something like
> 
> ```
> from roman_datamodels import datamodels as rdm
> from roman_datamodels import maker_utils
> 
> l2 = maker_utils.mk_level2_image(shape=(2000, 2000))
> l2_im = rdm.ImageModel(l2)
> ```
> 
> Please let us know if this does what you need.

```python
from roman_datamodels import datamodels as rdm
from roman_datamodels.maker_utils import mk_datamodel

l2 = mk_datamodel(rdm.ImageModel, shape=(2000, 2000))
```
Is a better way to do this.
