### ISSUE TITLE
Datamodels constructors should raise an exception if the top level node of an asdf file has the wrong type.

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/roman_datamodels#34]
The current code does not check to see, when using a data model constructor, that the asdf file provided has a top node that has a type consistent with the data model class. The implementation to provide this should allow for specific cases where they are mismatched for conversion functions to be used, but this is expected to be infrequent.

Currently there exists a stub method to do this, but it currently does nothing.

**Comment by nden** [comment]
Fixed in #35
