### ISSUE TITLE
Add String Length Enforcement to Validate

### ISSUE THREAD

**Issue by PaulHuwe** [spacetelescope/roman_datamodels#342]
Presently, it is possible to populate strings (maybe numbers as well?) to lengths larger than the archive catalog will support. This should be enforced in validate.

**Comment by schlafly** [comment]
I talked about this with @braingram today.  He suggested that it could be as easy as adding "maxLength" following type to all of our string entries.

We would introduce the complication that we would then store the type twice, once for the asdf file and once for the database, and naturally we would want to keep those two values in sync.  We already have this problem at some level; we currently store things like "integer" as the type, and then again "int" as the datatype for the archive.  So we could alternatively just choose to keep the current explicit listing of both types for the files and types for the database, at the cost of a lot of redundancy.

Brett's example:
```
{
    "$schema": "https://json-schema.org/draft04/schema",
    "type": "string",
    "maxLength": 4,
}
```
