### ISSUE TITLE
Error during json serialization

### ISSUE THREAD

**Issue by antonioaddis** [spacetelescope/roman_datamodels#355]
I have a pydantic object containing references to an asdf L2 data object. I am trying to serialize the pydantic object in a json-based string using the function [model_dump_json ](https://docs.pydantic.dev/latest/api/base_model/#pydantic.BaseModel.model_dump_json), but I got this issue:

pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'roman_datamodels.stnode._node.DNode'>

do you have any insights to fix that? should I create a custom serializer for the DNode object maybe? I'm currently using version 0.17.0. I appreciate any help you can provide. Thank you :pray: :pray:

**Comment by braingram** [comment]
Thanks for opening the issue.

Is there a minimum example that we can use to reproduce the issue?

If so would you provide the python version and a `pip list` of the environment (so we can check using the same versions of roman-datamodels, pydantic, asdf, etc...)?

We don't have any code that uses pydantic with roman-datamodels. It would be helpful to see the code that integrates these two libraries if that is possible.

**Comment by antonioaddis** [comment]
Issue closed as it does not apply to this repository.
