### ISSUE TITLE
shape argument to mk_level2_image doesn't work as described

### ISSUE THREAD

**Issue by schlafly** [spacetelescope/roman_datamodels#377]
mk_level2_image(...) has a shape argument that is in part intended to allow level 2 images with different numbers of resultants to be created.  The following lines

https://github.com/spacetelescope/roman_datamodels/blob/5e996c37648bac7fa0ac3c4d5e0ce5b8ddaeb69a/src/roman_datamodels/maker_utils/_datamodels.py#L101-L102

need to be in the opposite order in order for this to work.  Currently mk_level2_image(3, 4088, 4088) makes an amp33 image that is 4088 x 4096 x 128 in size, while 3 x 4096 x 128 is the expected result.  The issue is that n_groups is shape[0], but shape is cut down to shape[1:3] before n_groups is assigned, so n_groups ends up being 4088 in this case at present.

**Comment by braingram** [comment]
What do you think about removing the support for 3 length shape input? It's redundant to providing a 2d shape + n_groups. We could:
- remove the if block
- (optionally) add a check that `len(shape) == 2`

**Comment by schlafly** [comment]
That would work for me; when I stumbled across this I initially tried to use n_groups, but spelled it wrong and got annoyed that it wasn't doing anything.  So I tried to go through shape instead and started getting confused.

Ordinarily I would oppose the API churn, but apparently the the 3D shape argument hasn't seen much use!
