### ISSUE TITLE
The area array should be removed from the test utils

### ISSUE THREAD

**Issue by sosey** [spacetelescope/roman_datamodels#41]
The area array is not be stored with level 2 data, that array should be removed from functions like `mk_level2_image`, along with anywhere else it is used.

https://github.com/spacetelescope/roman_datamodels/blob/main/src/roman_datamodels/testing/utils.py#L302

**Comment by ddavis-stsci** [comment]
The area arrays are moved to the area ref file
https://github.com/spacetelescope/roman_datamodels/pull/44
