### ISSUE TITLE
Data model constructors should return object instance used in constructor if right type

### ISSUE THREAD

**Issue by perrygreenfield** [spacetelescope/roman_datamodels#51]
Currently if one supplies an existing instance of a datamodel (say RampModel) to one of the datamodel constructors (say RampModel), and the instance is the same type as the constructor, the constructor should return that instance. Currently it raises an error.

This may require some trickery to effectively replace self with the instance (I will have to brush up on this)

**Comment by nden** [comment]
Fixed in #52
