### ISSUE TITLE
DOC: datamodels stuff should be here not in pipeline docs

### ISSUE THREAD

**Issue by pllim** [spacetelescope/roman_datamodels#81]
https://roman-pipeline.readthedocs.io/en/latest/roman/datamodels/models.html

For a user that only cares about the output file, not running the pipeline, they won't look there.

**Comment by ddavis-stsci** [comment]
But folks running the pipeline will care so I think the information in the roman-pipeline docs is appropriate. 
If you only care about roman_datamodels the information is at 
https://roman-datamodels.readthedocs.io/en/latest/
